### ISSUE TITLE
Spinnaker Halyard Support

### ISSUE THREAD

**Issue by kaitea** [segmentio/aws-okta#192]
The EKS feature works great and we are able to run kubectl commands like so:

`aws-okta exec <my-profile> -- kubectl get pods --all-namespaces`

however, when running `hal deploy apply`, it fails to run successfully due to auth error with eks

It would be great to add halyard support so we can commands like so as well:
`aws-okta exec <my-profile> -- hal deploy apply`

**Comment by nickatsegment** [comment]
It's been a while since I've used `hal`. Does it shell out to kubectl to do the initial bootstrapping? Does it read your kubeconfig file?

One thing that might help is to modify your kubeconfig to include `aws-okta` in the `exec` block:

```
users:
- name: <cluster arn>
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - exec
      - <aws-okta profile>
      - --
      - aws-iam-authenticator
      - token
      - -i
      - <cluster name>
      command: aws-okta
      env: null
```

If `hal` shells out to your local `kubectl`, then that should solve any env var propagation problems. (It's a good idea anyway, saves a ton of wrapping.)
